### PR TITLE
Add source map support (fixes #4)

### LINKED ISSUE #4: Gulp-sourcemaps support
Any chance of adding in [gulp-sourcemaps](https://www.npmjs.org/package/gulp-sourcemaps) support? Would love to bundle this in. Thanks!

### PR DESCRIPTION
**Pull request by lahmatiy**

### CODE REVIEW

**Comment by ben-eb** [comment]
Looks good, although wouldn't it be simpler to delegate the bulk of this to `gulp-sourcemaps`? https://github.com/floridoo/gulp-sourcemaps

**Comment by lahmatiy** [comment]
Nothing prevents you to use plugin with `gulp-sourcemaps`.
Actually I tested `gulp-csso` with it. My config that works fine:

```js
var gulp = require('gulp');
var concat = require('gulp-concat');
var sourcemaps = require('gulp-sourcemaps');
var csso = require('gulp-csso');
 
gulp.task('css', function() {
  return gulp.src('*.css')
    .pipe(sourcemaps.init())
      .pipe(concat('all.css'))
      .pipe(csso())
    .pipe(sourcemaps.write())
    .pipe(gulp.dest('dist'));
});
```

**Comment by lahmatiy** [comment]
Some clarification. `gulp-csso` attaches source map JSON to file only. If input source map is presented plugin uses it to remap map generated by csso before attaching. That's it.

**Comment by ben-eb** [comment]
I'd rather use `vinyl-sourcemaps-apply`. It's less maintenance going forward, easier for users to grok, and consistent with the rest of the ecosystem. We don't need to reinvent the wheel here.

https://github.com/floridoo/gulp-sourcemaps#example

If you are changing the main API to expose an object instead of a boolean we should release sourcemap support in a major release.

**Comment by lahmatiy** [comment]
> If you are changing the main API to expose an object instead of a boolean

What do you mean?

**Comment by ben-eb** [comment]
Sorry, forgot *options* in front of *object* there. I'm pointing out that the current API expects a boolean to disable structure minimisation, changing it to an options object means a breaking change is all.

**Comment by lahmatiy** [comment]
I care about backward compatibility https://github.com/lahmatiy/gulp-csso/blob/master/index.js#L65-L67

**Comment by ben-eb** [comment]
Ah ok, then the documentation should be labelled as such. Would prefer this format if that's OK.

https://github.com/postcss/postcss-devtools#api

**Comment by lahmatiy** [comment]
Is it ok now?

**Comment by lahmatiy** [comment]
I fixed your notes (in case you missed it)

**Comment by ben-eb** [comment]
Thanks! :+1:

**Pull request merged**
